# Generated by Django 2.1.5 on 2019-02-25 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(help_text='ID', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(help_text='First Name', max_length=35)),
                ('last_name', models.CharField(help_text='Last Name', max_length=35)),
                ('phone_number', models.CharField(help_text='10 digit Mobile Number', max_length=10, unique=True)),
                ('email_id', models.EmailField(help_text='Email ID', max_length=254, unique=True)),
                ('profile_picture', models.ImageField(default=None, help_text='Profile Picture', null=True, upload_to='Profile Pictures/')),
                ('training_dataset', models.FileField(default=None, help_text='Training Dataset .zip file', null=True, upload_to='Training Dataset/')),
                ('user_since', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the person active?')),
                ('is_superuser', models.BooleanField(default=False, help_text='Is the person a superuser?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_commencement_timestamp', models.DateTimeField(help_text='Date and Time when lecture begins.')),
                ('lecture_ended_timestamp', models.DateTimeField(help_text='Date and Time when lecture ended.')),
                ('present', models.BooleanField(default=False, help_text='Student Present?')),
                ('concession', models.BooleanField(default=False, help_text='Attendance obtained via concession?')),
                ('modified', models.BooleanField(default=False, help_text='Attendance modified by teacher?')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Department name.', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], help_text='Choose the day.', max_length=10)),
                ('beginning_time', models.TimeField(verbose_name='Lecture beginning time')),
                ('ending_time', models.TimeField(verbose_name='Lecture ending time')),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B')], help_text='Choose the division', max_length=1)),
                ('batch', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('FC', 'Full Class')], default='FC', help_text='Choose the batch', max_length=2)),
                ('department', models.ForeignKey(help_text="Faculty's Department", on_delete=django.db.models.deletion.CASCADE, to='database.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Subject Code.', max_length=25, unique=True)),
                ('name', models.CharField(help_text='Subject name.', max_length=254, unique=True)),
                ('initials', models.CharField(help_text="Subject's initials.", max_length=25, unique=True)),
                ('department', models.ForeignKey(help_text="Subject's Department", on_delete=django.db.models.deletion.CASCADE, to='database.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(choices=[('F.Y. B.tech', "First Year of Bachelor's of Technology"), ('S.Y. B.tech', "Second Year of Bachelor's of Technology"), ('T.Y. B.tech', "Third Year of Bachelor's of Technology"), ('L.Y. B.tech', "Last Year of Bachelor's of Technology")], help_text='choose an option.', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person', models.OneToOneField(help_text='Person who this Admin is', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('person', models.OneToOneField(help_text='Person who this Faculty is', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('room_number', models.CharField(blank=True, default='', help_text='Room Number. eg: B-201', max_length=10)),
                ('department', models.ForeignKey(help_text="Faculty's Department", on_delete=django.db.models.deletion.CASCADE, to='database.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person', models.OneToOneField(help_text='Person who this Student is', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('division', models.CharField(help_text='Division, eg: B', max_length=1)),
                ('batch', models.CharField(help_text="Student's Batch, eg: B2", max_length=2)),
                ('department', models.ForeignKey(help_text="Student's Department", on_delete=django.db.models.deletion.CASCADE, to='database.Department')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(help_text='Subject for which Year students?', on_delete=django.db.models.deletion.DO_NOTHING, to='database.Year'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(help_text='Lecture Subject.', on_delete=django.db.models.deletion.DO_NOTHING, to='database.Subject'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.ForeignKey(help_text='Subject for which Year students?', on_delete=django.db.models.deletion.DO_NOTHING, to='database.Year'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(help_text='Lecture Subject.', on_delete=django.db.models.deletion.DO_NOTHING, to='database.Subject'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='faculty',
            field=models.ForeignKey(help_text="Faculty who's teaching for this schedule.", on_delete=django.db.models.deletion.DO_NOTHING, to='database.Faculty'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='faculty',
            field=models.ForeignKey(help_text="Faculty who's teaching for this lecture.", on_delete=django.db.models.deletion.DO_NOTHING, to='database.Faculty'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(help_text='Student whose Attendance is being marked', on_delete=django.db.models.deletion.DO_NOTHING, to='database.Student'),
        ),
    ]
