# Generated by Django 2.1.5 on 2019-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, help_text='Profile Picture', null=True, upload_to='Profile Pictures/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='training_dataset',
            field=models.FileField(blank=True, default=None, help_text='Training Dataset .zip file', null=True, upload_to='Training Dataset/'),
        ),
    ]
