# Generated by Django 2.1.5 on 2019-02-25 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190225_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.ForeignKey(default=None, help_text='Subject for which Year students?', on_delete=django.db.models.deletion.DO_NOTHING, to='database.Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Information Technology', 'Information Technology'), ('Mechanical engineering', 'Mechanical engineering'), ('Electronics & Telecommunication Engineering', 'Electronics & Telecommunication Engineering'), ('Electronics Engineering', 'Electronics Engineering'), ('Science & Humanities', 'Science & Humanities')], help_text='Department name.', max_length=254, unique=True),
        ),
    ]
