# Generated by Django 2.1.5 on 2019-03-04 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190304_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lecture_commencement_timestamp',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lecture_ended_timestamp',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(default='', help_text='Schedule for this attendance', on_delete=django.db.models.deletion.DO_NOTHING, to='database.Schedule'),
            preserve_default=False,
        ),
    ]
