# Generated by Django 2.1.5 on 2019-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190304_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/media/Profile Pictures/default/default.png', help_text='Profile Picture', null=True, upload_to='Profile Pictures/'),
        ),
    ]
