# Generated by Django 2.1.5 on 2019-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190307_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(help_text='Roll Number', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
