# Generated by Django 2.1.7 on 2019-04-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190307_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lecture_class',
            field=models.CharField(default='-', help_text='Class Room in which lecture will be conducted', max_length=10),
        ),
    ]
