# Generated by Django 2.1.7 on 2019-04-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_schedule_lecture_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_class', models.CharField(default='-', help_text='Class Room in which lecture will be conducted', max_length=10)),
                ('url', models.URLField()),
            ],
        ),
    ]
