# Generated by Django 2.1.7 on 2019-04-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
